version: '3.8'

networks:
  junior-rest-api:
    driver: bridge

volumes:
  rest-mysql:

services:
  nginx-task-one:
    image: nginx:latest
    container_name: nginx-frontend-part
    ports:
      - '${WEB_PORT}:80'
    restart: unless-stopped
    volumes:
      # Это файлы сайтов
      - ./frontend/dist:/usr/share/nginx/html
      # Файлы логов
      - ./frontend/logs:/var/log/nginx

  php-fpm:
    container_name: php-junior-rest
    # image: docker.io/bitnami/php-fpm:latest
    build:
      context: ./backend/fpm
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend/app:/var/www/html
    networks:
      - junior-rest-api

  nginx:
    image: nginx:latest
    container_name: nginx-junior-rest
    restart: unless-stopped
    ports:
      - "${API_PORT}:80"
    volumes:
      # Это конфиги для хостов
      - ./backend/nginx-config:/etc/nginx/conf.d
      # Это файлы сайтов
      - ./backend/app:/var/www/html
      - ./backend/logs:/var/log/nginx
    networks:
      - junior-rest-api

  mysql:
    image: mysql:latest
    container_name: mysql-server-junior-rest
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - rest-mysql:/var/lib/mysql
    networks:
      - junior-rest-api

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-junior-rest
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - junior-rest-api

  adminer:
    image: adminer:latest
    container_name: db-adminer-junior-rest
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - junior-rest-api