version: "3.8"

networks:
  junior-rest-api:
    driver: bridge

volumes:
  rest-mysql:

services:
  php-fpm:
    container_name: php-junior-rest
    # image: docker.io/bitnami/php-fpm:latest
    build:
      context: ./fpm
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
      # Конфиги для php
      - ./fpm/xdebug.ini:/etc/php/8.2/mods-available/xdebug.ini
    extra_hosts:
      - "xdebug-phpstorm.my:192.168.100.30"
    networks:
      - junior-rest-api

  nginx:
    image: nginx:latest
    container_name: nginx-junior-rest
    restart: unless-stopped
    ports:
      - "8201:80"
    volumes:
      # Это конфиги для хостов
      - ./nginx-config:/etc/nginx/conf.d
      # Это файлы сайтов
      - ./app:/var/www/html
      - ./logs:/var/log/nginx
    networks:
      - junior-rest-api

  mysql:
    image: mysql:latest
    container_name: mysql-server-junior-rest
    restart: always
    ports:
      - 8202:3306
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dump-task:/docker-entrypoint-initdb.d
      - rest-mysql:/var/lib/mysql
    networks:
      - junior-rest-api

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-junior-rest
    restart: always
    ports:
      - 8203:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - junior-rest-api

  adminer:
    image: adminer:latest
    container_name: db-adminer-junior-rest
    restart: always
    ports:
      - 8204:8080
    networks:
      - junior-rest-api
